### ISSUE TITLE
Better handling of Tidal 429 errors

### ISSUE THREAD

**Issue by d3mystified** [d3mystified/lidarr-tidal#5]
So as to not erase existing Lidarr data.

Also, why does the Tidal API return 404 when the album exists? Example:

```
Fetching album from Tidal for id: 000299946127
Error retrieving album 000299946127: Album unavailable
Fetching album from Tidal for id: 000143213444
Error retrieving album 000143213444: Album unavailable
```

But all these exist (because the IDs came from Tidal).

**Comment by d3mystified** [comment]
Ah, rate limit as suspected:

```
>>> session.album('000143213444')
Traceback (most recent call last):
  File "/home/ada/.local/lib/python3.10/site-packages/tidalapi/request.py", line 151, in request
    request.raise_for_status()
  File "/home/ada/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.tidal.com/v1/albums/000143213444?...
```

I might need a local caching layer, maybe a sqlite DB.
